const teamDescriptions = {
    "Argentina": "Dolorem etincidunt est dolorem etincidunt. Dolorem sit sed magnam consectetur. Magnam quaerat quaerat sit quisquam. Aliquam sit ipsum sed dolorem. Voluptatem eius aliquam voluptatem modi. Adipisci voluptatem non quisquam labore neque dolor. Neque sit quaerat numquam adipisci quaerat. Amet dolore ut quiquia magnam. Sed ut sit aliquam aliquam dolorem ut.",
    "Australia": "Modi ut consectetur modi adipisci. Adipisci porro quaerat ipsum. Dolorem amet numquam dolore dolore est sit. Eius neque sed sit voluptatem adipisci. Amet dolor tempora ipsum dolore labore. Quiquia labore quisquam adipisci. Aliquam voluptatem tempora dolor quiquia labore adipisci.",
    "Belgium": "Dolorem ut neque consectetur dolore neque. Aliquam labore magnam neque numquam. Modi numquam ut amet quaerat adipisci. Non quisquam consectetur sit neque. Consectetur etincidunt sit modi adipisci sit tempora. Neque porro consectetur dolore magnam consectetur.",
    "Brazil": "Amet non etincidunt est magnam. Ut sed sed sed consectetur adipisci quaerat quaerat. Dolor eius ipsum ipsum etincidunt adipisci velit velit. Dolorem non etincidunt sed sed dolor quiquia voluptatem. Sit est tempora labore est. Velit dolore labore dolore consectetur. Eius sed dolor porro. Dolore modi etincidunt velit consectetur dolor. Quisquam velit velit neque. Consectetur velit dolorem eius dolor numquam dolore.",
    "Cameroon": "Aliquam modi consectetur dolor aliquam adipisci labore. Velit etincidunt numquam quaerat non porro modi. Quaerat sit adipisci eius sit sed tempora ipsum. Dolorem non voluptatem porro neque consectetur. Quiquia sit dolore eius eius. Est dolor neque dolor tempora amet sit. Velit dolorem aliquam dolor sit porro. Quisquam etincidunt sed porro.",
    "Canada": "Dolorem aliquam modi dolorem. Amet quisquam neque voluptatem porro sed. Non eius porro dolor adipisci adipisci modi non. Magnam tempora tempora non voluptatem porro. Consectetur adipisci quaerat est consectetur adipisci.",
    "Costa Rica": "Modi amet modi quaerat etincidunt quaerat quisquam velit. Quisquam sed modi dolorem neque. Quisquam etincidunt consectetur dolor. Modi dolorem amet consectetur. Quaerat est etincidunt porro. Non aliquam quiquia dolore magnam tempora tempora. Modi est aliquam quaerat. Numquam porro neque dolorem.",
    "Croatia": "Sed est est voluptatem sit etincidunt dolore magnam. Non etincidunt non sit amet. Voluptatem ipsum ut modi neque. Neque porro tempora dolorem porro quaerat. Porro magnam sed consectetur sed velit quaerat. Eius eius velit numquam amet porro aliquam. Adipisci porro quisquam modi porro labore dolor. Est eius ut dolorem non quiquia porro dolorem. Consectetur adipisci dolor ut porro.",
    "Denmark": "Neque adipisci sed etincidunt dolorem quisquam aliquam sed. Aliquam tempora dolorem quaerat porro dolorem magnam dolorem. Amet adipisci numquam adipisci etincidunt magnam dolor. Quiquia ipsum numquam dolorem sed sit porro. Dolor adipisci consectetur est numquam numquam dolor eius. Voluptatem aliquam quiquia porro quisquam velit sed eius.",
    "Ecuador": "Sed dolorem dolorem amet. Consectetur ut voluptatem voluptatem. Tempora labore quisquam neque sed non velit. Adipisci quaerat aliquam sit. Labore etincidunt dolor sit sit velit aliquam. Dolore velit quaerat sit.",
    "England": "Quiquia est non quaerat velit sit. Amet quiquia est etincidunt quiquia labore. Numquam labore ut amet eius ut. Tempora ipsum quisquam consectetur dolorem adipisci quiquia adipisci. Sed amet sit ut dolor aliquam.",
    "France": "Aliquam quiquia velit est quaerat. Sed quiquia consectetur magnam velit velit dolorem. Non porro dolorem labore. Tempora amet sit non voluptatem etincidunt magnam. Numquam ipsum adipisci quiquia consectetur consectetur eius sit. Dolor adipisci tempora dolorem velit dolor dolor neque. Magnam non modi dolorem quisquam labore neque. Quisquam ut quiquia amet sed ut dolorem non. Aliquam voluptatem numquam dolorem ipsum etincidunt sit. Dolorem tempora velit sit dolorem velit.",
    "Germany": "Voluptatem tempora non ipsum aliquam consectetur. Amet quaerat numquam dolorem etincidunt magnam. Labore aliquam tempora aliquam velit dolore eius ipsum. Magnam est labore sit. Velit etincidunt est magnam aliquam neque numquam. Quaerat voluptatem consectetur est modi. Porro porro sed porro etincidunt ipsum. Sit porro aliquam modi ut numquam non. Magnam dolorem est numquam. Quaerat voluptatem velit quaerat voluptatem quaerat numquam dolore.",
    "Ghana": "Magnam quiquia non quiquia. Voluptatem est dolor quiquia labore. Sit magnam modi sed aliquam neque neque. Amet amet magnam dolorem sed. Eius dolorem voluptatem ut adipisci dolore. Porro velit ipsum voluptatem voluptatem numquam. Non dolor ipsum quiquia magnam dolorem. Porro consectetur labore velit modi consectetur numquam. Dolore magnam quisquam dolore. Velit quiquia quiquia est non magnam labore.",
    "Iran": "Labore magnam eius magnam velit sed dolorem quisquam. Amet etincidunt est consectetur sit quisquam est. Labore labore ut numquam adipisci dolore ut. Quiquia labore tempora aliquam. Velit est quisquam amet neque neque sed. Non quaerat consectetur non voluptatem modi modi. Quiquia amet adipisci neque. Ut ut dolore quaerat. Velit aliquam sed dolor dolor.",
    "Japan": "Quiquia porro consectetur eius ut neque voluptatem. Ipsum dolore voluptatem ut velit. Modi porro etincidunt modi ipsum aliquam aliquam modi. Adipisci labore velit labore numquam. Ut neque magnam porro sed amet. Modi tempora consectetur consectetur. Voluptatem aliquam voluptatem non. Dolorem dolor sed neque non modi ipsum. Velit non amet amet.",
    "Mexico": "Dolorem magnam sed consectetur dolor. Dolore ipsum est velit labore. Eius adipisci adipisci consectetur consectetur est sit. Voluptatem tempora sit neque quiquia. Dolor velit consectetur porro. Quisquam ipsum labore dolore consectetur ipsum consectetur. Neque amet modi ut etincidunt quiquia etincidunt labore.",
    "Morocco": "Quisquam quaerat sit sed etincidunt est. Est sed neque non ut. Tempora ipsum dolor voluptatem labore magnam. Eius quiquia dolorem labore ut velit neque. Dolorem porro porro eius neque. Quisquam dolor amet est non eius dolore.",
    "Netherlands": "Sit dolor aliquam tempora voluptatem numquam velit quiquia. Sed etincidunt porro consectetur eius velit quaerat. Amet quaerat labore amet modi. Consectetur velit eius voluptatem eius modi. Voluptatem dolor velit est. Quiquia magnam sit eius quiquia. Sit tempora quisquam quaerat. Amet amet modi magnam est velit. Magnam eius aliquam est.",
    "Poland": "Ipsum adipisci quisquam ut etincidunt dolorem dolor voluptatem. Quaerat sit etincidunt numquam etincidunt non. Ut ipsum ipsum est. Eius tempora magnam adipisci tempora. Ut porro quisquam sit. Eius eius adipisci dolor. Sed labore labore etincidunt dolorem. Consectetur velit numquam quaerat. Tempora magnam sit numquam voluptatem.",
    "Portugal": "Velit tempora modi porro. Sed modi eius non voluptatem voluptatem eius non. Amet tempora labore labore consectetur dolore eius quisquam. Dolore etincidunt sed aliquam voluptatem. Numquam est quisquam ut voluptatem quisquam. Labore aliquam quisquam est. Labore non eius labore. Tempora est voluptatem modi velit non. Consectetur etincidunt velit ut quaerat tempora amet porro. Consectetur velit amet consectetur aliquam neque porro.",
    "Qatar": "Adipisci ipsum velit voluptatem. Magnam eius aliquam quisquam etincidunt. Eius quisquam ipsum dolore velit consectetur. Aliquam sed numquam quaerat est adipisci modi. Quaerat est est voluptatem est dolorem non. Sit magnam adipisci voluptatem amet sed. Aliquam aliquam neque quaerat. Non porro sit etincidunt tempora dolor dolor sed.",
    "Saudi Arabia": "Dolor amet numquam numquam. Dolorem ut amet velit consectetur. Aliquam aliquam est est. Porro etincidunt eius sit non. Numquam voluptatem sit etincidunt aliquam numquam. Amet consectetur ipsum modi consectetur sit. Consectetur tempora dolorem sed tempora eius non sed.",
    "Senegal": "Eius amet modi amet dolore dolor. Quisquam neque labore tempora ut velit. Consectetur dolor quiquia porro. Non numquam aliquam aliquam consectetur. Dolor numquam modi voluptatem voluptatem. Aliquam dolor sed eius tempora. Aliquam quisquam est tempora aliquam quiquia. Quaerat eius magnam eius. Non est numquam neque ipsum ut.",
    "Serbia": "Ut aliquam dolor sed. Labore adipisci porro dolor. Neque dolore dolorem sed velit labore. Est modi non non consectetur ut quaerat. Neque numquam velit eius quaerat sit velit. Modi ipsum sit ipsum. Porro eius eius quisquam tempora. Neque quaerat quaerat numquam tempora. Quaerat quisquam velit etincidunt adipisci numquam.",
    "South Korea": "Non quisquam eius eius. Adipisci etincidunt porro dolore sed adipisci. Porro modi ipsum quaerat quiquia aliquam est. Eius consectetur labore sed eius. Quiquia dolore labore consectetur voluptatem modi.",
    "Spain": "Dolor aliquam quisquam voluptatem consectetur. Consectetur magnam non porro dolorem ipsum. Porro ut velit est ipsum aliquam numquam. Adipisci neque etincidunt ut. Dolorem dolor dolore etincidunt quaerat quiquia. Non quaerat etincidunt sed est ipsum. Amet modi porro sed. Numquam etincidunt dolorem est dolorem eius est velit. Numquam voluptatem magnam labore est adipisci neque. Dolorem quisquam amet tempora tempora porro tempora.",
    "Switzerland": "Neque dolor consectetur modi voluptatem amet quisquam consectetur. Aliquam etincidunt sed velit etincidunt aliquam. Magnam velit porro magnam. Aliquam magnam eius labore. Velit ut ut neque consectetur voluptatem etincidunt aliquam. Quisquam aliquam dolor tempora quaerat ipsum dolor. Ut quiquia ipsum quiquia adipisci ipsum.",
    "Tunisia": "Labore dolore numquam etincidunt ut quiquia. Non numquam neque dolor est eius ut. Tempora est labore modi velit. Aliquam numquam quaerat amet. Adipisci etincidunt tempora dolore. Dolore ipsum est eius sit tempora. Ut voluptatem dolor ipsum consectetur. Porro ut magnam aliquam est adipisci etincidunt. Magnam adipisci quaerat dolorem quisquam ut sed etincidunt. Est quiquia ut quisquam.",
    "United States": "Dolore sed quisquam velit sit. Labore ipsum tempora consectetur amet amet. Est quisquam quiquia dolore modi. Dolore dolor est ut amet eius consectetur. Quisquam adipisci magnam non dolore est.",
    "Uruguay": "Adipisci quaerat quiquia velit eius. Modi est neque numquam quaerat porro. Dolore quaerat ipsum eius eius dolor porro quisquam. Voluptatem eius non eius dolorem dolore tempora labore. Quaerat voluptatem ut ipsum sed adipisci labore est. Numquam dolor etincidunt adipisci quaerat amet tempora. Aliquam quisquam labore porro porro amet porro neque.",
    "Wales": "Dolore est dolore numquam ut. Modi quiquia eius voluptatem amet quaerat est. Adipisci quiquia numquam dolor voluptatem quaerat. Sit neque non aliquam etincidunt non magnam. Magnam aliquam etincidunt velit etincidunt dolor. Ut labore quaerat est. Quisquam aliquam velit non ut quiquia. Ipsum magnam velit quaerat. Modi consectetur est est dolore sit. Quisquam neque numquam dolore consectetur non.",
}

const coaches = {
    "Argentina": "Lionel Scaloni",
    "Australia": "Graham Arnold",
    "Belgium": "Roberto Martínez",
    "Brazil": "Adenor Leonardo Bacchi",
    "Cameroon": "Rigobert Song",
    "Canada": "John Herdman",
    "Costa Rica": "Luis Fernando Suárez",
    "Croatia": "Zlatko Dalić",
    "Denmark": "Kasper Hjulmand",
    "Ecuador": "Gustavo Alfaro",
    "England": "Gareth Southgate",
    "France": "Didier Deschamps",
    "Germany": "Hansi Flick",
    "Ghana": "Otto Addo",
    "Iran": "Carlos Queiroz",
    "Japan": "Hakime Moriyasu",
    "Mexico": "Gerardo Martino",
    "Morocco": "Walid Regragui",
    "Netherlands": "Louis van Gaal",
    "Poland": "Czesław Michniewicz",
    "Portugal": "Fernando Santos",
    "Qatar": "Félix Sánchez",
    "Saudi Arabia": "Hervé Renard",
    "Senegal": "Aliou Cissé",
    "Serbia": "Dragan Stojković",
    "South Korea": "Paulo Bento",
    "Spain": "Luis Enrique",
    "Switzerland": "Murat Yakin",
    "Tunisia": "Jalel Kadri",
    "United States": "Gregg Berhalter",
    "Uruguay": "Diego Alonso",
    "Wales": "Rob Page",
}

const rosters = {}

export {teamDescriptions, coaches, rosters};